apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector: {{ include "common.labels" . | indent 4 }}
  ports:
  - port: 80
    targetPort: 4200
    nodePort: 30001